package io;

import java.io.File;
import java.io.FileOutputStream;

public class FileDeal {
	
	
	public static void main(String[] args) throws Exception{
		
	        File file=new File("clm.sh");
	        if(file.exists()){
	        	file.delete();
	        }
	        file.createNewFile();
	        
	        FileOutputStream out=new FileOutputStream(file,true);
	        StringBuffer sb = new StringBuffer();
	        String hang = "\n";
	        sb
	        .append("#!/bin/sh                                                                                                                          ").append(hang)
	        .append("echo 'begin time:' `date +%Y%m%d%H%M%S`                                                                                            ").append(hang)
	        .append("BEGIN_TIME=`date +%s`                                                                                                              ").append(hang)
	        .append("YYYYMM=`date +%Y%m`                                                                                                                ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("SHELL_PATH=/home/aicrm/tags_clm                                                                                                    ").append(hang)
	        .append("FTP_IP=10.10.140.162                                                                                                               ").append(hang)
	        .append("FTP_USR=ftpuser                                                                                                                    ").append(hang)
	        .append("FTP_PWD=Ftpuser-123                                                                                                                ").append(hang)
	        .append("FTP_DIR=/cross/tagsfile                                                                                                            ").append(hang)
	        .append("USR_PWD='poweruser/User-162@shcrmbcv1'                                                                                             ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("cd $SHELL_PATH                                                                                                                     ").append(hang)
	        .append("echo '第一步：ftp取数据'                                                                                                           ").append(hang)
	        .append("##FTP 取数据                                                                                                                       ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("ftp -n<<EOF                                                                                                                        ").append(hang)
	        .append("open ${FTP_IP}                                                                                                                     ").append(hang)
	        .append("user ${FTP_USR} ${FTP_PWD}                                                                                                         ").append(hang)
	        .append("prompt off                                                                                                                         ").append(hang)
	        .append("binary                                                                                                                             ").append(hang)
	        .append("cd ${FTP_DIR}                                                                                                                      ").append(hang)
	        .append("mget *${YYYYMM}.txt                                                                                                                ").append(hang)
	        .append("mdelete *${YYYYMM}.txt                                                                                                             ").append(hang)
	        .append("close                                                                                                                              ").append(hang)
	        .append("bye                                                                                                                                ").append(hang)
	        .append("EOF                                                                                                                                ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("##FTP END                                                                                                                          ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("echo '第二步：sqlldr入库，并使用sqlplus入库'                                                                                       ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("#设置客户端字符集和oralce一致                                                                                                      ").append(hang)
	        .append("#setenv NLS_LANG \"SIMPLIFIED CHINESE_CHINA.ZHS16GBK\"                                                                               ").append(hang)
	        .append("ALL_FILE=`ls |grep $YYYYMM`                                                                                                        ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("LOG_FILE=tags_log.log                                                                                                              ").append(hang)
	        .append("DATA_BAD=tags_bad.bad                                                                                                              ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("for DATA_FILE in $ALL_FILE                                                                                                         ").append(hang)
	        .append("do                                                                                                                                 ").append(hang)
	        .append(" if [ -f $cmd ]                                                                                                                    ").append(hang)
	        .append(" then                                                                                                                              ").append(hang)
	        .append("   ##产生控制文件tags.ctl                                                                                                          ").append(hang)
	        .append("   FILE=tags.ctl                                                                                                                   ").append(hang)
	        .append("   if [ -f $FILE ]                                                                                                                 ").append(hang)
	        .append("   then                                                                                                                            ").append(hang)
	        .append("   	rm $FILE                                                                                                                      ").append(hang)
	        .append("   fi                                                                                                                              ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("   AttrId=${DATA_FILE:0:${#DATA_FILE}-11}                                                                                          ").append(hang)
	        .append("   DateTime=${VAR:(-10)}                                                                                                           ").append(hang)
	        .append("   DateTime=${DateTime:0:6}                                                                                                        ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("   echo \"load data                                           \" >> $FILE                                                            ").append(hang)
	        .append("   echo \"CHARACTERSET ZHS16GBK                               \" >> $FILE                                                            ").append(hang)
	        .append("   echo \"into table party.SF_CLM_USER_TAGS_help              \" >> $FILE                                                            ").append(hang)
	        .append("   echo \"TRUNCATE                                             \" >> $FILE                                                           ").append(hang)
	        .append("   echo \"fields terminated by \",\" optionally enclosed by '\"' \" >> $FILE                                                         ").append(hang)
	        .append("   echo \"(bill_id,attr_id CONSTANT \"${AttrId}\",attr_value)   \" >> $FILE                                                            ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("   ###sqlldr 入库                                                                                                                  ").append(hang)
	        .append("   sqlldr userid=$USR_PWD control=tags.ctl data=$DATA_FILE  log = $LOG_FILE bad=$DATA_BAD  rows=100000,errors=100,bindsize=20971520").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("echo '第二步：sqlplus入库  指标: '${AttrId}                                                                                        ").append(hang)
	        .append("   ####sqlplus 将数据插入到各个分表中                                                                                              ").append(hang)
	        .append("sqlplus $USR_PWD >>./test.log<<SQLSCOPE                                                                                            ").append(hang)
	        .append("set pagesize 0 feedback off verify off heading off echo off                                                                        ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("set colsep $sep;                                                                                                                   ").append(hang)
	        .append("set echo off;                                                                                                                      ").append(hang)
	        .append("set feedback off;                                                                                                                  ").append(hang)
	        .append("set heading off;                                                                                                                   ").append(hang)
	        .append("set pagesize 0;                                                                                                                    ").append(hang)
	        .append("set linesize 1000;                                                                                                                 ").append(hang)
	        .append("set numwidth 12;                                                                                                                   ").append(hang)
	        .append("set termout off;                                                                                                                   ").append(hang)
	        .append("set trimout on;                                                                                                                    ").append(hang)
	        .append("set trimspool on;                                                                                                                  ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("spool $fileTmp;                                                                                                                    ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("declare                                                                                                                            ").append(hang)
	        .append("v_sql varchar2(1024);                                                                                                              ").append(hang)
	        .append("v_date varchar2(12);                                                                                                               ").append(hang)
	        .append("begin                                                                                                                              ").append(hang)
	        .append("  select to_char(sysdate,'yyyymm') into v_date from dual;                                                                          ").append(hang)
	        .append("for i in 0..9 loop                                                                                                                 ").append(hang)
	        .append("  v_sql:='insert into party.sf_clm_user_tags_'||i||'_'||v_date||                                                                   ").append(hang)
	        .append("  ' select bill_id, attr_id, attr_value, null, sysdate, 1                                                                          ").append(hang)
	        .append("    from party.sf_clm_user_tags_help                                                                                               ").append(hang)
	        .append("   where mod(substr(bill_id, length(bill_id), 1), 10) = '||i;                                                                      ").append(hang)
	        .append("   dbms_output.put_line(v_sql);                                                                                                    ").append(hang)
	        .append("  execute immediate v_sql;                                                                                                         ").append(hang)
	        .append("  commit;                                                                                                                          ").append(hang)
	        .append("  dbms_output.put_line(i);                                                                                                         ").append(hang)
	        .append("end loop;                                                                                                                          ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("exception                                                                                                                          ").append(hang)
	        .append(" when others then                                                                                                                  ").append(hang)
	        .append("   rollback;                                                                                                                       ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("end;                                                                                                                               ").append(hang)
	        .append("/                                                                                                                                  ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("spool off;                                                                                                                         ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("exit;                                                                                                                              ").append(hang)
	        .append("SQLSCOPE                                                                                                                           ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("echo '第二步：备份数据到bak目录'                                                                                                   ").append(hang)
	        .append("	 ###        sqlplus 结束                                                                                                          ").append(hang)
	        .append("	                                                                                                                                  ").append(hang)
	        .append("	 ###将处理的文件备份到bak目录，bak目录，同一个指标，只保留一份数据                                                                ").append(hang)
	        .append("	 cd $SHELL_PATH                                                                                                                   ").append(hang)
	        .append("	 cd ./bak                                                                                                                         ").append(hang)
	        .append("	 COUNT=`ls |grep $AttrId |wc -l`                                                                                                  ").append(hang)
	        .append("	 if [ $COUNT -gt 0 ]                                                                                                              ").append(hang)
	        .append("	 then                                                                                                                             ").append(hang)
	        .append("	 	ls |grep $AttrId |xargs rm *                                                                                                    ").append(hang)
	        .append("	 fi                                                                                                                               ").append(hang)
	        .append("	                                                                                                                                  ").append(hang)
	        .append("	 cd ..                                                                                                                            ").append(hang)
	        .append("	 mv $DATA_FILE ./bak                                                                                                              ").append(hang)
	        .append("	 ###处理备份结束                                                                                                                  ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append(" fi                                                                                                                                ").append(hang)
	        .append("done                                                                                                                               ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("###处理配置文件  由于没有配置shpub库的tns，这段逻辑需要使用java代码入库.这直接做数据处理                                           ").append(hang)
	        .append("TAGSCONFIG=tags_config.txt                                                                                                         ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("####                                                                                                                               ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("                                                                                                                                   ").append(hang)
	        .append("##                                                                                                                                 ").append(hang)
	        .append("echo 'end time:' `date +%Y%m%d%H%M%S`                                                                                              ").append(hang)
	        .append("END_TIME=`date +%s`                                                                                                                ").append(hang)
	        .append("echo 'cost second' `expr $END_TIME - $BEGIN_TIME`                                                                                  ").append(hang) ;
	        
	        out.write(sb.toString().getBytes("GBK"));

	        out.close();
	        System.out.println("finish!");
	    }
	
}
